Repository camptocamp/helm-common, pull requests merged in 2022-12, with the labels that each got.

#93 Configure Mend Bolt
  .editorconfig
  .whitesource
Labels: chore

#95 GEO-6100: add logic for range over services
  templates/_helpers.tpl
  tests/expected.yaml
Labels: enhancement

#96 Fix missing trim to serviceName
  templates/_helpers.tpl
Labels: bug
